services:
    main:
      build: .
      environment:
        - YT_DLP_BINARY=""
        - PORT="3000"
      volumes:
        - ./data:/src/data
        - ./dist:/src/dist
      ports:
        - "0.0.0.0:3000:3000"